# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :run_appstore_build do
    gym(
        project: "AppStore-iOS.xcodeproj", #get from scheme name near run button
        configuration: "Debug", # or staging or release config file
        scheme: "AppStore-iOS",
        silent: true,
        clean: true, #// clean and build
        skip_archive: true, 
    )
  end
end
